### PR TITLE
try to fix rultor config

### PR DESCRIPTION
**Pull request by blackout314**
@yegor256 i cant try it :( i'm totally blind

#22

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#21` is not assigned, can't get performer

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@blackout314[/z](https://www.0crat.com/u/blackout314) this pull request is too small, just 5 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Pull request merged**
