### PR TITLE
#17

### PR DESCRIPTION
**Pull request by blackout314**
job #17
- try to fix rultor (i dont know how i can test in my fork, but i think is ok)
- added dynamic version replace on all html file, version is retrieved from package.json
- added dynamic dir for build from `npm start` to `grunt build` for avoid uncleaned work space problem

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#18](https://github.com/zold-io/zold.github.io/issues/18) is now in scope, role is `REV`

**Comment by blackout314** [comment]
@rultor deploy

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zold-io/zold.github.io/issues/18#issuecomment-395043262); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#18](https://github.com/zold-io/zold.github.io/issues/18); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by blackout314** [comment]
@rultor deploy

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zold-io/zold.github.io/issues/18#issuecomment-395362538); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Pull request merged**
