### PR TITLE
Task11

### PR DESCRIPTION
**Pull request by blackout314**
task #11 
blink every time node is updated

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#32](https://github.com/zold-io/zold.github.io/issues/32) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#32](https://github.com/zold-io/zold.github.io/issues/32); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@blackout314 seems to be a bug in the build. Let me fix

**Comment by yegor256** [comment]
@rultor merge

**Comment by blackout314** [comment]
@yegor256 not my issue
```
31mERROR0m: node_modules/table/dist/validateTableData.js; puzzle at line #49; @todo found, but puzzle can't be parsed, most probably because @todo is not followed by a puzzle marker, as this page explains: https://github.com/yegor256/pdd#how-to-format. If you can't understand the cause of this issue or you don't know how to fix it, please submit a GitHub issue, we will try to help you: https://github.com/yegor256/pdd/issues. This tool is still in its beta version and we will appreciate your feedback. Here is where you can find more documentation: https://github.com/yegor256/pdd/blob/master/README.md.
```

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#32` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#32](https://github.com/zold-io/zold.github.io/issues/32) is now out of scope

**Comment by blackout314** [comment]
@yegor256 task #11

**Pull request merged**
