### PR TITLE
Blink every time a node is updated

### LINKED ISSUE #11: Blink every time we update a node
Let's blick the item on the list (in `#remotes`) every time we fetch the data from the node in `/map.html`, in order to show that this list is being updated in real-time mode. How exactly we will "blick" is up to the HTML designer.

### PR DESCRIPTION
**Pull request by blackout314**
in this task i do
* cache for first hit, after ever GET i cached results for "browser refresh". every call cache last result (main node info and main node remotes) #12 
* i've add a link to nodename #30
* i've added blink every update #11

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#31](https://github.com/zold-io/zold.github.io/issues/31) is now in scope, role is `REV`

**Comment by blackout314** [comment]
fix #30 too

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#31](https://github.com/zold-io/zold.github.io/issues/31); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#31` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#31](https://github.com/zold-io/zold.github.io/issues/31) is now out of scope

**Pull request closed without merging**
