### PR TITLE
Configure sass link task #34

### PR DESCRIPTION
**Pull request by blackout314**
configured and add in pipeline the sasslinter
task #34

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#38](https://github.com/zold-io/zold.github.io/issues/38) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#38](https://github.com/zold-io/zold.github.io/issues/38); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@blackout314 why can't we use _all_ rules? What is the point of defining a subset of them?

**Comment by blackout314** [comment]
@yegor256 are right subset of rules 👍 i'm a frontend

**Comment by yegor256** [comment]
@blackout314 I didn't understand :) What is the point of defining the rules for SASS lint? Let's just let it go with the full set and complain about as many problems as it can find.

**Comment by blackout314** [comment]
@yegor256 as you wish :) if you want i can drop all rules

**Comment by blackout314** [comment]
@yegor256 all rules on sasslinter (some like ordered prop are useless)

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#38` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#38](https://github.com/zold-io/zold.github.io/issues/38) is now out of scope

**Pull request merged**
