### PR TITLE
task #13

### PR DESCRIPTION
**Pull request by blackout314**
all nodes in table 👍 and not in `<ul>` list

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#20](https://github.com/zold-io/zold.github.io/issues/20) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#20](https://github.com/zold-io/zold.github.io/issues/20); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#20` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#20](https://github.com/zold-io/zold.github.io/issues/20) is now out of scope

**Comment by yegor256** [comment]
@rultor deploy

**Comment by blackout314** [comment]
@yegor256 i think rultor is stucked
https://github.com/zold-io/zold.github.io/blob/master/.rultor.yml#L16-L18

**Comment by blackout314** [comment]
i think the problem is
```
TEMPDIR=$(mktemp -d)
TARGET=$(TEMPDIR) npm start
git checkout gh-pages
cp -R ${TEMPDIR}/* .
```

**Comment by yegor256** [comment]
@rultor stop

**Pull request merged**
