### PR TITLE
severity 2 for sasslint

### PR DESCRIPTION
**Pull request by blackout314**
@yegor256 i do a set of standard severity 2 on warning

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#62](https://github.com/zold-io/zold.github.io/issues/62) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#62](https://github.com/zold-io/zold.github.io/issues/62); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#62](https://github.com/zold-io/zold.github.io/issues/62); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@blackout314 what will happen when they introduce a new rule? We will have to update our code? This is not an optimal solution. Can't we somehow catch the output from sasslint and fail the build if it has "warning" text?

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#62` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#62](https://github.com/zold-io/zold.github.io/issues/62) is now out of scope

**Comment by blackout314** [comment]
@yegor256 no, the only way for fail the warning is update severity to 2
no other solution

**Pull request closed without merging**
